# Generated by Django 5.2.14 on 2026-05-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('event_type', models.CharField(choices=[('store', 'Evento na loja'), ('external', 'Evento externo'), ('promotion', 'Promoção'), ('workshop', 'Workshop'), ('adoption', 'Feira de adoção')], max_length=15, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descrição curta')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Imagem')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Banner')),
                ('start_date', models.DateTimeField(verbose_name='Data de início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de término')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Local')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('online_link', models.URLField(blank=True, verbose_name='Link online')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Imagem')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='promotions/banners/', verbose_name='Banner')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentual'), ('fixed', 'Valor fixo'), ('free_shipping', 'Frete grátis')], max_length=15, verbose_name='Tipo de desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do desconto')),
                ('coupon_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código do cupom')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compra mínima')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de usos')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Vezes utilizado')),
                ('start_date', models.DateTimeField(verbose_name='Início')),
                ('end_date', models.DateTimeField(verbose_name='Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('applicable_categories', models.ManyToManyField(blank=True, to='catalog.category', verbose_name='Categorias')),
                ('applicable_products', models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
    ]
