[tool.poetry]
name = "gateen-petshop"
version = "0.1.0"
description = "Sistema completo para Gateen Petshop"
authors = ["Seu Nome"]

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0"
pillow = "^10.3"
django-environ = "^0.11"
django-crispy-forms = "^2.1"
crispy-bootstrap5 = "^2024.2"
django-allauth = "^0.63"
whitenoise = "^6.6"
psycopg2-binary = "^2.9"
stripe = "^9.0"
django-extensions = "^3.2"
django-debug-toolbar = "^4.3"
reportlab = "^4.2"
jazzmin = "^3.0"

[tool.poetry.dev-dependencies]
black = "^24.0"
flake8 = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"