# Generated by Django 5.2.14 on 2026-05-11 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos')),
                ('lifetime_points', models.IntegerField(default=0, verbose_name='Pontos acumulados no total')),
                ('level', models.CharField(default='bronze', max_length=20, verbose_name='Nível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta Fidelidade',
                'verbose_name_plural': 'Contas Fidelidade',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da regra')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('rule_type', models.CharField(choices=[('brand_purchase', 'Compra por marca'), ('product_purchase', 'Compra de produto específico'), ('amount_spent', 'Valor gasto'), ('category_purchase', 'Compra por categoria')], max_length=20, verbose_name='Tipo de regra')),
                ('reward_type', models.CharField(choices=[('gift_product', 'Produto brinde'), ('discount_percent', 'Desconto percentual'), ('loyalty_points', 'Pontos de fidelidade')], max_length=20, verbose_name='Tipo de recompensa')),
                ('trigger_quantity', models.PositiveIntegerField(default=2, verbose_name='Quantidade necessária')),
                ('trigger_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo')),
                ('reward_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de desconto')),
                ('reward_points', models.PositiveIntegerField(default=0, verbose_name='Pontos de recompensa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('reward_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_rules', to='catalog.product', verbose_name='Produto brinde')),
                ('trigger_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Marca gatilho')),
                ('trigger_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_rules', to='catalog.product', verbose_name='Produto gatilho')),
            ],
            options={
                'verbose_name': 'Regra de Fidelidade',
                'verbose_name_plural': 'Regras de Fidelidade',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Ganho'), ('redeem', 'Resgate'), ('expire', 'Expirado'), ('bonus', 'Bônus')], max_length=10)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'verbose_name': 'Transação de Fidelidade',
                'ordering': ['-created_at'],
            },
        ),
    ]
