# Generated by Django 5.2.14 on 2026-05-11 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('period', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('annual', 'Anual')], default='monthly', max_length=15, verbose_name='Período')),
                ('food_bags_per_month', models.PositiveIntegerField(default=0, verbose_name='Sacos de ração/mês')),
                ('grooming_sessions_per_month', models.PositiveIntegerField(default=0, verbose_name='Banhos e tosas/mês')),
                ('includes_health_plan', models.BooleanField(default=False, verbose_name='Inclui plano de saúde')),
                ('health_plan_details', models.TextField(blank=True, verbose_name='Detalhes do plano de saúde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('color', models.CharField(default='#E85D26', max_length=7, verbose_name='Cor do card')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plano de Serviço',
                'verbose_name_plural': 'Planos de Serviço',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Benefício')),
                ('is_included', models.BooleanField(default=True, verbose_name='Incluído')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plans.serviceplan')),
            ],
            options={
                'verbose_name': 'Benefício do Plano',
                'verbose_name_plural': 'Benefícios do Plano',
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('pending', 'Pendente')], default='pending', max_length=15, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data de término')),
                ('food_bags_used', models.PositiveIntegerField(default=0, verbose_name='Sacos usados no mês')),
                ('grooming_sessions_used', models.PositiveIntegerField(default=0, verbose_name='Banhos usados no mês')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pet', verbose_name='Pet')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.serviceplan', verbose_name='Plano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Plano do Usuário',
                'verbose_name_plural': 'Planos dos Usuários',
            },
        ),
    ]
