# Generated by Django 5.2.14 on 2026-05-19 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('bath', 'Banho'), ('grooming', 'Tosa'), ('bath_grooming', 'Banho + Tosa')], max_length=20, verbose_name='Serviço')),
                ('scheduled_at', models.DateTimeField(verbose_name='Data e horário')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('done', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Status')),
                ('used_plan_session', models.BooleanField(default=False, verbose_name='Descontou sessão do plano')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.pet', verbose_name='Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('user_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='plans.userplan', verbose_name='Plano utilizado')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
